import {
  RunnerConfig,
  RunnerGenerateParams,
  RunnerGenerateResult,
  RunnerModel,
  RunnerProvider,
} from "./types";

interface CacheEntry {
  key: string;
  response: string;
  createdAt: number;
}

const DUMMY_MODELS: RunnerModel[] = [
  { name: "dummy-form-v1", provider: "dummy", description: "Deterministic generator" },
  { name: "dummy-form-v2", provider: "dummy", description: "Deterministic generator + rating field" },
];

const CACHE_LIMIT = 25;

export class LlmRunner {
  private config: RunnerConfig;
  private cache: CacheEntry[] = [];

  constructor(config?: Partial<RunnerConfig>) {
    this.config = {
      provider: config?.provider || "dummy",
      modelName: config?.modelName || DUMMY_MODELS[0].name,
      cacheEnabled: config?.cacheEnabled ?? true,
    };
  }

  getConfig(): RunnerConfig {
    return this.config;
  }

  setConfig(next: Partial<RunnerConfig>) {
    this.config = { ...this.config, ...next };
  }

  async listModels(provider = this.config.provider): Promise<RunnerModel[]> {
    if (provider === "dummy") {
      return DUMMY_MODELS;
    }

    if (typeof window === "undefined" || typeof window.ollama === "undefined") {
      return [];
    }

    const response = await window.ollama.getModels();
    if (!response.success) {
      return [];
    }
    return (response.data?.models || []).map((model: { name: string }) => ({
      name: model.name,
      provider: "ollama" as const,
    }));
  }

  async generate(params: RunnerGenerateParams): Promise<RunnerGenerateResult> {
    const startedAt = performance.now();
    const provider = this.config.provider;
    const modelName = params.modelName || this.config.modelName;
    const cacheKey = `${provider}::${modelName}::${params.system || ""}::${params.prompt}`;

    if (this.config.cacheEnabled) {
      const cached = this.cache.find((entry) => entry.key === cacheKey);
      if (cached) {
        return {
          success: true,
          data: { response: cached.response },
          stats: {
            latencyMs: Math.round(performance.now() - startedAt),
            cached: true,
            provider,
            modelName,
          },
        };
      }
    }

    let responseText = "";
    if (provider === "dummy") {
      responseText = this.generateDummy(params.prompt, modelName);
    } else {
      if (typeof window === "undefined" || typeof window.ollama === "undefined") {
        return { success: false, error: "Ollama extension is not available." };
      }
      const result = await window.ollama.generate({
        model: modelName,
        prompt: params.prompt,
        system: params.system,
        format: params.format,
        stream: false,
      });
      if (!result.success || !result.data?.response) {
        return { success: false, error: result.error || "Generation failed." };
      }
      responseText = result.data.response;
    }

    if (this.config.cacheEnabled) {
      const next = [{ key: cacheKey, response: responseText, createdAt: Date.now() }, ...this.cache];
      this.cache = next.slice(0, CACHE_LIMIT);
    }

    return {
      success: true,
      data: { response: responseText },
      stats: {
        latencyMs: Math.round(performance.now() - startedAt),
        cached: false,
        provider,
        modelName,
      },
    };
  }

  private generateDummy(prompt: string, modelName: string): string {
    const normalized = prompt.toLowerCase();
    const fields: Array<{ type: string; label: string; required?: boolean; options?: string[] }> = [
      { type: "ShortText", label: "Name", required: true },
      { type: "Email", label: "Email", required: true },
    ];

    if (normalized.includes("feedback") || normalized.includes("message")) {
      fields.push({ type: "LongText", label: "Message", required: true });
    }

    if (normalized.includes("event")) {
      fields.push({ type: "Date", label: "Preferred date" });
      fields.push({ type: "Number", label: "No. of attendees" });
    }

    if (modelName === "dummy-form-v2") {
      fields.push({
        type: "Dropdown",
        label: "Satisfaction",
        options: ["Excellent", "Good", "Average", "Poor"],
      });
    }

    return JSON.stringify(
      {
        title: "AI Generated Form",
        description: `Generated by ${modelName}`,
        fields,
      },
      null,
      2,
    );
  }
}

declare global {
  interface Window {
    ollama?: {
      getModels: () => Promise<any>;
      generate: (params: any) => Promise<any>;
    };
  }
}
